server:
  port: 8004

spring:
  application:
    name: cloud-provider-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:13306/springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: dimitre123
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181


mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: iceriver.springcloud.entities    # 所有Entity别名类所在包
