#spring:
## 配置数据源信息
#  datasource:
#  # 配置数据源类型
#    type: com.zaxxer.hikari.HikariDataSource
#    # 配置连接数据库信息
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:13306/mybatis_plus?characterEncoding=utf-8&useSSL=false
#    username: root
#    password: dimitre123
#
## 配置MyBatis日志
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  type-aliases-package: iceriver.mybatisplus.bean
##  扫描通用枚举的包
#  typeEnumsPackage: iceriver.mybatisplus.enums
